name: PJT-frontend # You can also change this to another name to avoid warning with existing group. 
services:
  frontend:
    container_name: PJT-frontend
    build: .
    ports:
      - ${NGINX_PORT}:5173
    networks:
      - PJT-front-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
networks:
  PJT-front-net: # Check by using `docker network ls` command
    external: true