name: PJT

services:
  frontend:
    container_name: PJT-frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_ENDPOINT: ${NEXT_PUBLIC_ENDPOINT}
    ports:
      - "${FRONTEND_PORT}:3001"
    networks:
      - PJT-net
    environment:
      NEXT_PUBLIC_ENDPOINT: ${NEXT_PUBLIC_ENDPOINT}

volumes:
  mysql-data:


networks:
  PJT-net:
    driver: bridge
