import type { Metadata } from 'next';
import { Geist, Geist_Mono, Poppins } from 'next/font/google';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import StyledComponentsRegistry from '@/app/lib/registry';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/app/styles/theme';
// ถ้าใช้ CssBaseline แนะนำเปิดใช้
// import CssBaseline from '@mui/material/CssBaseline';

const poppins = Poppins({
  weight: ['300','400','500','600','700'],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="th">
      <body className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {/* <CssBaseline /> */}
            <StyledComponentsRegistry>
              {children}
            </StyledComponentsRegistry>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
